### PR TITLE
(fix) Make comment's initials optional

### LINKED ISSUE #11: Make initials attribute from Comment type optional
The `initials` attribute should be optional when creating comments, as it is not required by Word. This can be seen in this [documentation link](https://www.datypic.com/sc/ooxml/e-w_comment-1.html), which shows that `w:initials` is an optional element.
https://github.com/FontoXML/docxml/blob/61dbd9c84ace68a166bf4524178db363f64a5ae3/src/files/CommentsXml.ts#L17

### PR DESCRIPTION
**Pull request by harvestcore**
This PR closes #11.

### CODE REVIEW

File: src/files/CommentsXml.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import { RelationshipsXml } from './RelationshipsXml.ts';
 type Comment = {
 	id: number;
 	author: string;
-	initials: string;
+	initials?: string | null;
```
Comment (ins426) [inline src/files/CommentsXml.ts:17]: Is this ` |null` really necessary?

Comment (harvestcore) [reply src/files/CommentsXml.ts:17]: The `?` is necessary as this property may be missing (e.g. creating a comment and not specifying the property). The `null` is also necessary as parsing a comment (`fromNode`, which uses FontoXPath) may produce a null value.

File: src/files/CommentsXml.test.ts [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+import { Paragraph } from '../components/Paragraph.ts';
+import { Text } from '../components/Text.ts';
+import { parse, serialize } from '../utilities/dom.ts';
+import { ALL_NAMESPACE_DECLARATIONS } from '../utilities/namespaces.ts';
+import { archive } from '../utilities/tests.ts';
+import { CommentsXml } from './CommentsXml.ts';
+import { ContentTypesXml } from './ContentTypesXml.ts';
+
+describe('Relationships', () => {
```
Comment (jogawebb) [inline src/files/CommentsXml.test.ts]: Did you use the `RelationshipsXml` file as a template for this one? Update this to say "`Comments`"

**Review by jogawebb — APPROVED** [review]

**Review by ins426 — APPROVED** [review]

File: src/files/CommentsXml.test.ts (hunk 2 above)
Comment (harvestcore) [reply src/files/CommentsXml.test.ts]: My b, I used the relationships files as a template.
